#!/usr/bin/env bash
#
# Copyright 2013 Apache Software Foundation
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.
#
set -o errexit
set -o nounset

PANTS_VERSION=0.0.14-dev2
if ! [[ -e build-support/pants-$PANTS_VERSION.pex ]]; then
  echo "Building pants.pex @ $PANTS_VERSION"
  ./build-support/pex \
    --requirement "twitter.pants==$PANTS_VERSION" \
    --entry-point twitter.pants.bin.pants_exe:main \
    -p build-support/pants-$PANTS_VERSION.pex.tmp
  mv build-support/pants-$PANTS_VERSION.pex.tmp build-support/pants-$PANTS_VERSION.pex  # 2PC
  echo "Built pants-$PANTS_VERSION.pex"
fi

exec ./build-support/pants-$PANTS_VERSION.pex "$@"
