#!/bin/sh -e
# Wrapper script for self-bootstrapping rbt.
# TODO(ksweeney): Use ./pants py here instead of virtualenv.
if ! [ -f build-support/rbtools/BOOTSTRAPPED ]; then
  echo Bootstrapping rbtools
  ./build-support/virtualenv build-support/rbtools
  source build-support/rbtools/bin/activate
  pip install RBTools==0.5
  touch build-support/rbtools/BOOTSTRAPPED
fi
source build-support/rbtools/bin/activate
exec rbt "$@"
