#!/usr/bin/env bash
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.
#
# Wrapper script for self-bootstrapping pex.
set -e

if which python2.7 >/dev/null; then
  PY=`which python2.7`
elif which python2.6 >/dev/null; then
  PY=`which python2.6`
else
  echo 'No python interpreter found on the path.  Python will not work!' 1>&2
  exit 1
fi

HERE=$(cd `dirname "${BASH_SOURCE[0]}"` && pwd)
PEX_REQ=$(grep pex $HERE/../3rdparty/python/requirements.txt)

if ! [ -f "$HERE/pex.venv/BOOTSTRAPPED" ] || \
    [ $(< "$HERE/pex.venv/BOOTSTRAPPED") != "$PEX_REQ" ]; then

  echo Bootstrapping $PEX_REQ
  rm -fr "$HERE/pex.venv"
  "$HERE/virtualenv" "$HERE/pex.venv"
  source "$HERE/pex.venv/bin/activate"
  python -m pip install $PEX_REQ
  echo $PEX_REQ > "$HERE"/pex.venv/BOOTSTRAPPED
fi
source "$HERE/pex.venv/bin/activate"
exec pex "$@"
