#!/usr/bin/env bash
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.
#
# Wrapper for self-bootstrapping virtualenv
set -ex
VIRTUALENV_VERSION=15.1.0

if which python2.7 >/dev/null; then
  PY=`which python2.7`
else
  echo 'No python2.7 interpreter found on the path.  Python will not work!' 1>&2
  exit 1
fi

echo "Using $PY" >&2

HERE=$(cd `dirname "${BASH_SOURCE[0]}"` && pwd)
if ! [ -f "$HERE/virtualenv-$VIRTUALENV_VERSION/BOOTSTRAPPED" ]; then
  pushd "$HERE"
  curl -LO https://pypi.io/packages/source/v/virtualenv/virtualenv-$VIRTUALENV_VERSION.tar.gz
  tar zxvf virtualenv-$VIRTUALENV_VERSION.tar.gz
  touch virtualenv-$VIRTUALENV_VERSION/BOOTSTRAPPED  # 2PC
  popd
fi

exec "$PY" "$HERE/virtualenv-$VIRTUALENV_VERSION/virtualenv.py" --no-download "$@"
