python_test_suite(
  name = 'all',
  dependencies = [
    pants('src/test/python/twitter/thermos/common:all'),
    pants('src/test/python/twitter/thermos/config:all'),
    pants('src/test/python/twitter/thermos/core:all'),
    pants('src/test/python/twitter/thermos/monitoring:all'),
  ]
)
