python_test_suite(
  name = 'all',
  dependencies = [
    pants('src/test/python/apache/aurora/admin:all'),
    pants('src/test/python/apache/aurora/client:all'),
    pants('src/test/python/apache/aurora/common:all'),
    pants('src/test/python/apache/aurora/config:all'),
    pants('src/test/python/apache/aurora/executor:all'),
  ]
)
