/**
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *     http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */
package com.twitter.common.logging;

import java.util.logging.Formatter;
import java.util.logging.Level;
import java.util.logging.LogRecord;

import com.google.common.collect.ImmutableMap;

/**
 * Log formatter to match the format generated by glog.
 *
 * @see Glog
 */
public class LogFormatter extends Formatter implements Glog.Formatter<LogRecord> {

  private static final ImmutableMap<Level, Glog.Level> LEVEL_LABELS =
      ImmutableMap.<Level, Glog.Level>builder()
          .put(Level.FINEST, Glog.Level.DEBUG)
          .put(Level.FINER, Glog.Level.DEBUG)
          .put(Level.FINE, Glog.Level.DEBUG)
          .put(Level.CONFIG, Glog.Level.INFO)
          .put(Level.INFO, Glog.Level.INFO)
          .put(Level.WARNING, Glog.Level.WARNING)
          .put(Level.SEVERE, Glog.Level.ERROR)
          .build();


  @Override
  public String format(final LogRecord record) {
    return Glog.formatRecord(this, record);
  }

  @Override
  public String getMessage(LogRecord record) {
    return formatMessage(record);
  }

  @Override
  public String getClassName(LogRecord record) {
    return record.getSourceClassName();
  }

  @Override
  public String getMethodName(LogRecord record) {
    return record.getSourceMethodName();
  }

  @Override
  public Glog.Level getLevel(LogRecord record) {
    return LEVEL_LABELS.get(record.getLevel());
  }

  @Override
  public long getTimeStamp(LogRecord record) {
    return record.getMillis();
  }

  @Override
  public long getThreadId(LogRecord record) {
    return record.getThreadID();
  }

  @Override
  public Throwable getThrowable(LogRecord record) {
    return record.getThrown();
  }
}
