python_test_suite(
  name = 'all',
  dependencies = [
    pants('src/test/python/twitter/aurora/admin:all'),
    pants('src/test/python/twitter/aurora/client:all'),
    pants('src/test/python/twitter/aurora/common:all'),
    pants('src/test/python/twitter/aurora/config:all'),
    pants('src/test/python/twitter/aurora/executor:all'),
  ]
)
