python_library(name = 'binding_helpers',
  sources = globs('*.py'),
  dependencies = [
    pants('3rdparty/python:pystachio'),
    pants('src/python/twitter/common/app'),
    pants('src/python/twitter/common/log'),
    pants('src/python/twitter/mesos/client:base'),
    pants('src/python/twitter/mesos/client:jenkins'),
    pants('src/python/twitter/mesos/config'),
    pants('src/python/twitter/packer'),
  ],
)


