#!/bin/bash
# Cuts a release tag (non -snapshot) from the current master and prints instructions for publishing
# it. The generated tag object is PGP-signed. Given a current master on 0.3.0-snapshot it will
# create a git history that looks like this:
# master~1 (0.3.0-snapshot) ----- master (0.4.0-snapshot)
#                            \--- release-0.4.0 (0.4.0) tag: 0.4.0 (0.4.0)
set -o errexit
set -o nounset

if [[ -n "`git status --porcelain`" ]]; then
  echo "!! Please run from a clean master."
  exit 1
elif [[ "`git rev-parse --abbrev-ref HEAD`" != master ]]; then
  echo "!! This script must be run from master."
  exit 1
elif [[ "`git rev-parse --show-toplevel`" != "$PWD" ]]; then
  echo "!! This script must be run from the root of the repository."
  exit 1
elif [[ -z "`git config user.signingkey`" ]]; then
  cat <<EOF
!! No GPG signing key is configured for this repository.

To configure one, find your code signing key's ID with

   gpg --list-secret-keys

Then configure it as the signing key for this repository with

   git config user.signingkey YOUR_KEY_ID
EOF
  exit 1
fi

function print_help_and_exit {
cat <<EOF
Aurora release tagging tool.

Usage: $0 [-h] [-d|-p|-m|-M]

  -h   Print this help message and exit
  -d   Create a new development tag (default)
  -p   Perform patch-level release
  -m   Perform minor-level release
  -M   Perform major-level release
EOF
exit 0
}

increment_level="dev"
while getopts ":phm" opt; do
  case $opt in
    d)
      increment_level="dev"
      ;;
    p)
      increment_level="patch"
      ;;
    m)
      increment_level="minor"
      ;;
    M)
      increment_level="major"
      ;;
    h)
      print_help_and_exit
      ;;
  esac
done

echo == Updating to latest master.
git pull
git fetch --tags

current_version=$(cat .auroraversion | tr '[a-z]' '[A-Z]')
if ! [[ $current_version =~ .*-SNAPSHOT ]]; then
  echo "!! This is not a SNAPSHOT branch (.auroraversion is $current_version)."
  exit 1
else
  major=`echo $current_version | cut -d. -f1`
  minor=`echo $current_version | cut -d. -f2`
  patch=`echo $current_version | cut -d. -f3 | cut -d- -f1`

  new_tagged_version="$major.$minor.$patch"

  if [[ $increment_level == "dev" ]]; then
    new_tagged_version="$major.$minor.$patch-dev$(date +%s)"
    new_snapshot_version="$major.$minor.$patch-SNAPSHOT"
    release_branch_name="devel-$new_tagged_version"
  elif [[ $increment_level == "patch" ]]; then
    new_snapshot_version="$major.$minor.$((patch + 1))-SNAPSHOT"
    release_branch_name="release-$major.$minor.$((patch + 1))"
  elif [[ $increment_level == "minor" ]]; then
    new_snapshot_version="$major.$((minor + 1)).0-SNAPSHOT"
    release_branch_name="release-$major.$((minor + 1)).0"
  elif [[ $increment_level == "major" ]]; then
    new_snapshot_version="$((major + 1)).0.0-SNAPSHOT"
    release_branch_name="release-$major.0.0"
  else
    echo "Unknown release increment $increment_level"
    exit 1
  fi
fi

if git rev-parse $new_tagged_version >/dev/null 2>&1; then
  echo "Tag $new_tagged_version already exists, aborting."
  exit 1
fi

current_rev=`git rev-parse HEAD`
function print_rollback_instructions {
cat <<EOF
!! Looks like something failed. That's okay, the world doesn't need to know.

To roll back your local repo you might need to run:
  git checkout master
  git reset --hard $current_rev
  git tag -d $new_tagged_version
  git branch -D $release_branch_name
EOF
}
trap print_rollback_instructions EXIT

function increment_aurora_version {
  if [[ $new_snapshot_version != $current_version ]]; then
    echo == Incrementing snapshot version on master.
    echo $new_snapshot_version > .auroraversion
    git add .auroraversion
    git commit -m "Incrementing snapshot version from $current_version to $new_snapshot_version."
  fi

  echo == Creating $release_branch_name branch.
  git checkout -b $release_branch_name $current_rev

  echo == Committing updated .auroraversion.
  echo $new_tagged_version > .auroraversion
  git add .auroraversion
  git commit -m "aurora-$new_tagged_version release."
}

increment_aurora_version

echo == Creating tag $new_tagged_version.
git tag -s -m "aurora-$new_tagged_version." $new_tagged_version

cat <<EOF
== Tag created.

After you've verified that everything looks good, publish the new tag by running:
   git checkout master
   git push origin master
   git push origin $new_tagged_version
EOF
trap '' EXIT # Unset error message handler.

exit 0
