#!/bin/bash
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.
#
#
# This script will download a release candidate and verify the gpg signature and
# checksums.
#
set -e

aurora_svn_dev_dist_url='https://dist.apache.org/repos/dist/dev/aurora'

# Get the current version string
if [[ ! -f .auroraversion ]]; then
  read -r -p "Apache Aurora version to verify: " current_version
else
  current_version=$(cat .auroraversion | tr '[a-z]' '[A-Z]')
fi

dist_name="aurora-${current_version}"
rc_dir=${dist_name}-verify
mkdir -p $rc_dir
cd $rc_dir

# Download KEYS file
curl -O ${aurora_svn_dev_dist_url}/KEYS

# Check and import the KEYS files
read -r -p "Import Apache Aurora GPG KEYS? [y/n]" response
response=${response,,}
if [[ $response =~ ^(yes|y| ) ]]; then
  gpg --import KEYS
fi

# Check out the rc
svn co ${aurora_svn_dev_dist_url}/${current_version} ${rc_dir}

# Verify GPG
gpg --verify ${dist_name}.tar.gz.asc ${dist_name}.tar.gz

# Verify MD5
gpg --print-md MD5 ${dist_name}.tar.gz | diff - ${dist_name}.tar.gz.md5

# Verify SHA
shasum ${dist_name}.tar.gz | diff - ${dist_name}.tar.gz.sha

exit 0
