#!/usr/bin/env bash
#
# Copyright 2014 Apache Software Foundation
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.
#
# Wrapper script for running isort
set -e

HERE=$(cd `dirname "${BASH_SOURCE[0]}"` && pwd)
CHECKSTYLE_VERSION=0.1.0

if ! [ -f "$HERE/checkstyle.venv/BOOTSTRAPPED" ] || \
    [ x`cat "$HERE/checkstyle.venv/BOOTSTRAPPED"` != x$CHECKSTYLE_VERSION ]; then
  echo Bootstrapping checkstyle @ $CHECKSTYLE_VERSION
  rm -fr "$HERE/checkstyle.venv"
  "$HERE/../virtualenv" "$HERE/checkstyle.venv"
  source "$HERE/checkstyle.venv/bin/activate"
  python -m pip install "twitter.checkstyle==$CHECKSTYLE_VERSION"
  echo $CHECKSTYLE_VERSION > "$HERE/checkstyle.venv/BOOTSTRAPPED"
fi

source "$HERE/checkstyle.venv/bin/activate"
exec twitterstyle "$@"
