# TODO(wickman) Support code-gen targets in setup_py

python_thrift_library(
  name = 'py-thrift',
  sources = ['thermos_internal.thrift'],
  provides = setup_py(
    name = 'twitter.gen.thermos',
    version = '0.0.0'
  )
)
